version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    
  nginx:
    container_name: nginx
    restart: always
    build:
        context: ..
        dockerfile: .devcontainer/nginx.Dockerfile
    volumes:
        - ../html:/var/www/public
        - ../nginx:/var/log/nginx
        # - ./nginx:/etc/nginx/conf.d
    ports:
        - "80:80"
        - "443:443"
