version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

  nginx:
    container_name: nginx
    restart: always
    build:
      context: ..
      dockerfile: .devcontainer/nginx.Dockerfile
    volumes:
      - type: bind
        source: ../html
        target: /var/www/public
        read_only: true
    ports:
      - "8080:80"
      - "443:443"
    command: [ "nginx", "-g", "daemon off;" ]
